name: Copilot setup steps (pre-firewall)
version: 1
# NOTE: This setup ONLY runs validation steps - NO doc regeneration
# These steps are frozen to prevent recursive loops in CI
# For manual doc updates, use: npm run regen-docs (developer only)
steps:
  - name: Use Node 20
    run: |
      node -v || true
      npm -v || true
  - name: Install deps
    run: npm ci
  - name: Install Playwright browsers
    run: |
      npx playwright install chromium
      npx playwright install webkit
  - name: Typecheck & Lint
    run: |
      npm run typecheck --if-present
      npm run lint --if-present
  - name: Build
    run: npm run build
  - name: Smoke preview
    run: |
      (npm run preview &) && sleep 2
      curl -sSf http://localhost:4173 > /dev/null
